name: studip-sync
version: git
summary: Synchronize files from Stud.IP
description: |
  Download and synchronize files and media from Stud.IP -- the campus management
  platform deployed at several German universities. Note that this project
  is currently only supported for the University of Göttingen but could work
  at other universities with similar authentication methods.

grade: devel
confinement: strict
base: core20

parts:
  studip-sync:
    plugin: python
    source: .
    build-packages:
        - on armhf: [zlib1g-dev, libxml2-dev, libxslt-dev, python-dev]
        - on arm64: [zlib1g-dev, libxml2-dev, libxslt-dev, python-dev]
        - on s390x: [zlib1g-dev, libxml2-dev, libxslt-dev, python-dev]
        - on ppc64el: [zlib1g-dev, libxml2-dev, libxslt-dev, python-dev]
    stage-packages: [rsync]
    build-environment:
        - SNAPCRAFT_PYTHON_INTERPRETER: python3.6

apps:
  studip-sync:
    command: env LC_ALL=C.UTF-8 LANG=C.UTF-8 $SNAP/bin/studip-sync
    plugs: [home, network, removable-media]
