#!/bin/bash

usage() {
    echo
    echo "Usage: $(basename "$0") [ OPTIONS... ] /path/to/studip/sync/dir"
    echo
    echo "OPTIONS:"
    echo "  -v   enable verbose output. Might print sensitive information!"
    echo "  -i   reads username and password from interactive prompt"
    echo "  -c   set alternative config directory"
    echo "  -h   display this help and exit"
    echo "  -p   remove 'dateiliste.csv' and 'filelist.csv'"
    echo "  -f   force remove 'dateiliste.csv' and 'filelist.csv'"
}

interactive=false
verbose=false
workdir="/tmp/studip-sync/workdir"
start_dir=$PWD
zipfile_name="$(head -c16 /dev/urandom | md5sum | cut -d' ' -f1)_st_ip.zip"
sync_dir=""
config_dir=""
keep_stats=true
force=false

while getopts "fpivhc:" opt; do
    case $opt in
        i)
            interactive=true
            ;;
        v)
            verbose=true
            ;;
        h)
            usage
            exit
            ;;
        c)
            config_dir="$OPTARG"
            ;;
        p)
            keep_stats=false
            ;;
        f)
            force=true
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))
sync_dir=$(realpath "$*")

if [ ! -d "$sync_dir" ]; then
    echo "'$sync_dir' is not a directory!"
    exit 1
fi

if $verbose; then
    RSYNC_DBG_FLAG="-v"
    CURL_DBG_FLAG="-v"
else
    CURL_DBG_FLAG="-s"
    RSYNC_DBG_FLAG=""
fi

if [ "$config_dir" != "" ]; then
    if [ ! -d "$config_dir" ]; then
        echo "'$config_dir' is not a directory!"
        exit 1
    fi
else
    config_dir="$HOME/.config/studip-sync"
    if [ ! -d "$config_dir" ]; then
        config_dir="/etc/studip-sync.conf.d"
    fi
    if [ ! -d "$config_dir" ]; then
        echo "No config directory found! Bye..."
        exit 1
    fi
fi

config_dir=$(realpath "$config_dir")
user_conf_file="$config_dir/user.conf"
courses_conf_file="$config_dir/courses.conf"

if [ ! -r "$courses_conf_file" ]; then
    echo "Courses configuration not found!"
    exit 1
fi

if $interactive; then
    read -rp "loginname: " loginname
    read -rsp "password: " password
    echo
else
    if [ ! -r "$user_conf_file" ]; then
        echo "User configuration not found!"
        exit 1
    fi
    source "$user_conf_file"
fi

mkdir -p "$workdir"
cd "$workdir" || exit 1

sso_url=$(curl $CURL_DBG_FLAG \
    -fLo tmp.html \
    --cookie-jar cookies.txt \
    --write-out %{url_effective} \
    "https://studip.uni-passau.de/studip/index.php?again=yes&sso=shib")

if [ $? -ne 0 ]; then
    echo "An error occured while connecting to Stud.IP!"
    exit 1
fi

curl $CURL_DBG_FLAG \
    -fLo SAMLResponse \
    --cookie-jar cookies.txt \
    --cookie cookies.txt \
    --data-urlencode "j_username=$loginname" \
    --data-urlencode "j_password=$password" \
    --data-urlencode "_eventId_proceed=" \
    "$sso_url"

if [ $? -ne 0 ]; then
    echo "An error occured while authenticating to the Central Authentication Service!"
    exit 1
fi

RelayState=$(grep --text RelayState SAMLResponse \
    | grep -Po 'value=".*?"' \
    | cut -d\" -f2 \
    | recode html..latin1)

SAMLResponse=$(grep --text SAMLResponse SAMLResponse \
    | grep -Po 'value=".*?"' \
    | cut -d\" -f2 \
    | recode html..latin1)

curl $CURL_DBG_FLAG \
    -fLo tmp.html \
    --cookie-jar cookies.txt \
    --cookie cookies.txt \
    --data-urlencode "RelayState=$RelayState" \
    --data-urlencode "SAMLResponse=$SAMLResponse" \
    "https://studip.uni-passau.de/Shibboleth.sso/SAML2/POST"

if [ $? -ne 0 ]; then
    echo "An error occured while authenticating to Stud.IP!"
    exit 1
fi

curl_flags=""
zip_files=( )
while read line; do
    if ! (echo $line | grep -qE "#|^$|^[[:blank:]]*$"); then
        course_name="$(echo $line | grep -Po "^.*?\ " | sed 's/\ $//')"
        url="$(echo $line | grep -o "https://.*$")"
        outfile="$course_name/$zipfile_name"
        curl_flags="$curl_flags -o $outfile $url"
        zip_files+=( $outfile )
        mkdir -p "$course_name"
    fi
done < <(cat $courses_conf_file)

curl $CURL_DBG_FLAG -fL --cookie cookies.txt $curl_flags

if [ $? -ne 0 ]; then
    echo "An error occured while downloading .zip archives!"
    exit 1
fi

rm cookies.txt tmp.html SAMLResponse

for f in "${zip_files[@]}"; do
    if [[ -f "$f" ]]; then
        dir=$(dirname "$f")
        extract_cmd="7z x -bd -y -o$dir $f"
        if $verbose; then
            $extract_cmd
        else
            $extract_cmd > /dev/null
        fi
        rm "$f"
        if ! $keep_stats; then
            rm -f "$dir/dateiliste.csv"
            rm -f "$dir/filelist.csv"
        fi
    fi
done

rsync $RSYNC_DBG_FLAG -rc -b --suffix="_$(date +%d.%m.%Y_%H+%M+%S).old" . "$sync_dir"

if $force; then
    find "$sync_dir" \( -name "dateiliste.csv" -o -name "filelist.csv" \) -exec rm "{}" \;
fi

cd "$start_dir" || exit 1
rm -r $workdir
